name: "Test slack-notifier"
on:
  pull_request:
  push:
    branches:
      - master
      - "releases/*"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: yarn install
      - run: yarn build
      # - uses: ./
      #   with:
      #     webHookUrl: ${{secrets.SLACK_HOOK}}
